#ifndef GUARD_CONSTANTS_SPARRING_H
#define GUARD_CONSTANTS_SPARRING_H

#define SPARRING_FUNC_INIT                  0
#define SPARRING_FUNC_GET_DATA              1
#define SPARRING_FUNC_SET_DATA              2
#define SPARRING_FUNC_SET_OPPONENT          3
#define SPARRING_FUNC_SET_BATTLE_WON        4
#define SPARRING_FUNC_GIVE_RIBBONS          5
#define SPARRING_FUNC_SAVE                  6
#define SPARRING_FUNC_GET_OPPONENT_INTRO    7
#define SPARRING_FUNC_NOP                   8
#define SPARRING_FUNC_NOP2                  9
#define SPARRING_FUNC_GET_CONTINUE_MENU_TYPE 10
#define SPARRING_FUNC_RESTORE_HELD_ITEMS 11
#define SPARRING_FUNC_RESET_SKETCH_MOVES 12
#define SPARRING_FUNC_GIVE_BATTLE_POINTS 13
#define SPARRING_FUNC_GET_FIRST_TYPE_WIN 14
#define SPARRING_FUNC_GET_TYPE_NAME 15
#define SPARRING_FUNC_CHECK_SYMBOL 16

#define SPARRING_DATA_WIN_STREAK         1
#define SPARRING_DATA_WIN_STREAK_ACTIVE  2
#define SPARRING_DATA_LVL_MODE           3
#define SPARRING_DATA_TYPE_MODE          4

#define RECORDYES_HEALYES 0
#define RECORDYES_HEALNO 1
#define RECORDNO_HEALYES 2
#define RECORDNO_HEALNO 3

#define SPARRING_MAX_NUM_RESTORE 2

#define SPARRING_REWARD_BP 3
#define SPARRING_REWARD_BONUS_ROUND 5
#define SPARRING_REWARD_BP_BONUS 20
#define SPARRING_REWARD_FIRST_BONUS 30
#define SPARRING_MIN_STREAK 5

#define SPARRING_LOST 0
#define SPARRING_QUIT 1

#define SPARRING_GET_NONE 0
#define SPARRING_GET_SILVER 1
#define SPARRING_GET_GOLD 2

#define MAX_SPARRING_STREAK UCHAR_MAX

#endif //GUARD_CONSTANTS_SPARRING_H
