#ifndef GUARD_CONSTANTS_SPARRING_H
#define GUARD_CONSTANTS_SPARRING_H

#define SPARRING_FUNC_INIT                  0
#define SPARRING_FUNC_GET_DATA              1
#define SPARRING_FUNC_SET_DATA              2
#define SPARRING_FUNC_SET_OPPONENT          3
#define SPARRING_FUNC_SET_BATTLE_WON        4
#define SPARRING_FUNC_GIVE_RIBBONS          5
#define SPARRING_FUNC_SAVE                  6
#define SPARRING_FUNC_GET_OPPONENT_INTRO    7
#define SPARRING_FUNC_NOP                   8
#define SPARRING_FUNC_NOP2                  9
#define SPARRING_FUNC_GET_CONTINUE_MENU_TYPE 10
#define SPARRING_FUNC_RESTORE_HELD_ITEMS 11
#define SPARRING_FUNC_RESET_SKETCH_MOVES 12

#define SPARRING_DATA_WIN_STREAK         1
#define SPARRING_DATA_WIN_STREAK_ACTIVE  2
#define SPARRING_DATA_LVL_MODE           3

#define RECORDYES_HEALYES 0
#define RECORDYES_HEALNO 1
#define RECORDNO_HEALYES 2
#define RECORDNO_HEALNO 3

#define SPARRING_MAX_NUM_RESTORE 2

#endif //GUARD_CONSTANTS_SPARRING_H
